name: Wheels

on:
  push:
    branches:
    - master

env:
  LIBGIT2_VERSION: 1.1.0

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
    - name: Checkout pygit2
      uses: actions/checkout@v2
      
    - uses: docker/setup-qemu-action@v1
      if: ${{ matrix.arch == 'aarch64' }}
      name: Set up QEMU

    - name: x86_64 wheels
      if: ${{ matrix.arch == 'x86_64' }}
      run: /bin/sh travis/build-all-manylinux-wheels.sh :x86_64
        
    - name: aarch64 wheels
      if: ${{ matrix.arch == 'aarch64' }}
      run: /bin/sh travis/build-all-manylinux-wheels.sh _aarch64

    - name: Save wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist/*.whl
        
  build-aarch64:
    name: "Test ${{ matrix.pyver }} aarch64 build wheel"
    strategy:
      matrix:
        arch: [aarch64]
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - run: |
        /bin/sh travis/build-all-manylinux-wheels.sh _aarch64
         

  macos:
    name: macos-${{ matrix.py.ver }}
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"
    strategy:
      fail-fast: false
      matrix:
        libgit2: ['maint/v1.1']
        py:
          - ver: '3.6'
            release: '3.6.8'  # last Python.org binary release
          - ver: '3.7'
            release: '3.7.9'  # last Python.org binary release
          - ver: '3.8'
            release: '3.8.7'
          - ver: '3.9'
            release: '3.9.1'
    steps:
    - name: Checkout pygit2
      uses: actions/checkout@v2

    - name: Setup python
      run: |
        PKG="python-${{ matrix.py.release }}-macosx10.9.pkg"
        URL="https://www.python.org/ftp/python/${{ matrix.py.release }}/$PKG"
        wget --no-verbose -N "$URL"
        sudo installer -pkg $PKG -target /
        export PATH=/Library/Frameworks/Python.framework/Versions/${{ matrix.py.ver }}/bin:$PATH
        echo "/Library/Frameworks/Python.framework/Versions/${{ matrix.py.ver }}/bin" >> $GITHUB_PATH
        which python3
        python3 -VV
        test "$(python3 -V)" = "Python ${{ matrix.py.release }}"

    - name: Build
      run: |
        /bin/sh build.sh wheel bundle test

    - name: Save wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: wheelhouse/*.whl

  pypi:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [linux, macos]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: wheels
        path: dist

    - name: Display structure of downloaded files
      run: ls -lh dist

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
